_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": windows-amd64
L2_lamb:
    value: 0.0005
activation_f:
    value: tanh
batch_size:
    value: 64
epochs:
    value: 5
init_mode:
    value: xavier
learning_rate:
    value: 0.0001
num_hidden:
    value: 5
num_neurons:
    value: 128
optimizer:
    value: nadam
