wandb_version: 1

L2_lamb:
  value: 0
activation_f:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 40
init_mode:
  value: random_uniform
learning_rate:
  value: 0.001
num_hidden:
  value: 4
num_neurons:
  value: 64
optimizer:
  value: momentum
