wandb_version: 1

L2_lamb:
  value: 0
activation_f:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 20
init_mode:
  value: random_uniform
learning_rate:
  value: 0.0001
num_hidden:
  value: 5
num_neurons:
  value: 32
optimizer:
  value: adam
