wandb_version: 1

L2_lamb:
  value: 0
activation_f:
  value: tanh
batch_size:
  value: 256
epochs:
  value: 5
init_mode:
  value: random_uniform
learning_rate:
  value: 0.0001
num_hidden:
  value: 5
num_neurons:
  value: 32
optimizer:
  value: nestorov
