wandb_version: 1

L2_lamb:
  value: 0.5
activation_f:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
init_mode:
  value: xavier
learning_rate:
  value: 0.001
num_hidden:
  value: 4
num_neurons:
  value: 128
optimizer:
  value: nadam
