wandb_version: 1

L2_lamb:
  value: 0
activation_f:
  value: relu
batch_size:
  value: 32
epochs:
  value: 40
init_mode:
  value: xavier
learning_rate:
  value: 0.0001
num_hidden:
  value: 4
num_neurons:
  value: 128
optimizer:
  value: momentum
