wandb_version: 1

L2_lamb:
  value: 0.5
activation_f:
  value: relu
batch_size:
  value: 64
epochs:
  value: 20
init_mode:
  value: random_normal
learning_rate:
  value: 0.0001
num_hidden:
  value: 5
num_neurons:
  value: 32
optimizer:
  value: nestorov
