wandb_version: 1

L2_lamb:
  value: 0.5
activation_f:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 20
init_mode:
  value: random_uniform
learning_rate:
  value: 0.001
num_hidden:
  value: 4
num_neurons:
  value: 128
optimizer:
  value: nadam
