wandb_version: 1

L2_lamb:
  value: 0.5
activation_f:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
init_mode:
  value: random_uniform
learning_rate:
  value: 0.0001
num_hidden:
  value: 5
num_neurons:
  value: 64
optimizer:
  value: RMSprop
