wandb_version: 1

L2_lamb:
  value: 0.0005
activation_f:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
init_mode:
  value: xavier
learning_rate:
  value: 0.0001
num_hidden:
  value: 3
num_neurons:
  value: 128
optimizer:
  value: sgd
