wandb_version: 1

L2_lamb:
  value: 0
activation_f:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
init_mode:
  value: random_normal
learning_rate:
  value: 0.0001
num_hidden:
  value: 3
num_neurons:
  value: 64
optimizer:
  value: momentum
