wandb_version: 1

L2_lamb:
  value: 0.5
activation_f:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
init_mode:
  value: xavier
learning_rate:
  value: 0.0001
num_hidden:
  value: 3
num_neurons:
  value: 64
optimizer:
  value: momentum
