wandb_version: 1

L2_lamb:
  value: 0.0005
activation_f:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 40
init_mode:
  value: random_normal
learning_rate:
  value: 0.001
num_hidden:
  value: 3
num_neurons:
  value: 128
optimizer:
  value: nadam
