wandb_version: 1

L2_lamb:
  value: 0.0005
activation_f:
  value: tanh
batch_size:
  value: 128
epochs:
  value: 20
init_mode:
  value: random_uniform
learning_rate:
  value: 0.001
num_hidden:
  value: 4
num_neurons:
  value: 32
optimizer:
  value: sgd
