wandb_version: 1

L2_lamb:
  value: 0.0005
activation_f:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 40
init_mode:
  value: random_normal
learning_rate:
  value: 0.0001
num_hidden:
  value: 5
num_neurons:
  value: 128
optimizer:
  value: momentum
