wandb_version: 1

L2_lamb:
  value: 0.0005
activation_f:
  value: relu
batch_size:
  value: 256
epochs:
  value: 5
init_mode:
  value: random_normal
learning_rate:
  value: 0.0001
num_hidden:
  value: 4
num_neurons:
  value: 64
optimizer:
  value: adam
