wandb_version: 1

L2_lamb:
  value: 0
activation_f:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
init_mode:
  value: xavier
learning_rate:
  value: 0.0001
num_hidden:
  value: 3
num_neurons:
  value: 32
optimizer:
  value: nadam
